easy_admin:
    design:
      brand_color: 'rgba(26, 188, 156, 0.85)'
      assets:
        favicon: '/assets/backend/favicon.png'
    site_name: 'CV Editor'
    user:
      name_property_path: 'email'
    entities:
#        # List the entity class name you want to manage
      CvFields:
        class: App\Entity\CvFields
      Contact:
        class: App\Entity\Contact
        list:
          fields:
            - 'id'
            - 'yourEmail'
            - 'message'
      User:
          class: App\Entity\User
          help: 'It takes so long to respond'
          list:
            fields:
              - 'id'
              - { property: 'email', type: 'email' }
              - 'roles'
          form:
            fields:
              - { property: 'email', type: 'email' }
              - { property: 'password', type: 'password' }
              - {property: 'roles', type: 'collection'}
          show:
            fields:
              - 'id'
              - { property: 'email', type: 'email' }
              - {property: 'roles', type: 'collection'}
          search:
            fields:
              - 'id'
              - { property: 'email', type: 'email' }
              - {property: 'roles', type: 'collection'}
      Skills:
          class: App\Entity\Skills